services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    environment:
      # This is the user that will be created in the postgres database
      POSTGRES_USER: docker
      # This is the password for the postgres user
      POSTGRES_PASSWORD: docker
      # This is the name of the database to create
      POSTGRES_DB: agents
    ports:
      - "5432:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql